server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: service-hi
    prefer-ip-address: true
info:
  app.name: eureka-client
  company.name: www.zhaowb.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$