spring:
  application:
    name: cloud-config-eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8770/eureka/
server:
  port: 8770